### ISSUE TITLE
Support full flow of the OAuth2 Authentication

### ISSUE THREAD

**Issue by vishalya** [trinodb/trino-python-client#103]
The JWT token authentication is good, but it leaves a decent amount of reusable code outside of the library.
My proposal is to add the full authenticaion support - `OAuth2Authentication`. The functionality would be similar to the JDBC driver to make the python API orthogonal wrt JDBC api.
 - Add a new Auth class, we can merge it with JWT auth which ever makes sense
 - Perform the OAuth2 based authentication and setup the http_seesion with token
 - I have added a new private authentcate method to the base class, not sure if it could be merged with the set_http_session or any other existing method.

**Comment by vishalya** [comment]
I was able to hack some working code here, with some refinement I can send a PR for it.
https://github.com/vishalya/trino-python-client/commit/e0c109c5296f4db739d3934038133e0036c0135c

**Comment by hashhar** [comment]
cc: @aalbu

**Comment by hashhar** [comment]
Fixed by https://github.com/trinodb/trino-python-client/pull/104
