### ISSUE TITLE
trino 0.307.0: AttributeError: module 'trino' has no attribute 'dbapi'

### ISSUE THREAD

**Issue by vinclei** [trinodb/trino-python-client#133]
When upgraded to trino 0.307.0, having below error:
AttributeError: module 'trino' has no attribute 'dbapi'

**Comment by hashhar** [comment]
Thank you for the report, it's fixed by https://github.com/trinodb/trino-python-client/commit/747654d9aa8cb7e281ddc2ae0c1460658547faf1 and 0.308.0 should be out soon.
