### ISSUE TITLE
ModuleNotFoundError: No module named 'trino.sqlalchemy'

### ISSUE THREAD

**Issue by mishbahr** [trinodb/trino-python-client#135]
Trying out latest version of `trino==0.308` from PyPy.

Looks like it does not include the `sqlalchemy` module.

Am I being a noob?

**Comment by hashhar** [comment]
Yes. You need to install the sqlalchemy extra. Like so `pip install 'trino[sqlalchemy]'`

And use as :

```python
 import sqlalchemy as sqla
 engine = sqla.create_engine('trino://user@localhost:8080/system')
 nodes = sqla.Table('nodes', sqla.MetaData(schema='runtime'), autoload=True, autoload_with=engine)
 connection = engine.connect()
 connection.execute(sqla.select([nodes])).fetchall()
```

**Comment by mishbahr** [comment]
The "extra" part is to install `sqlalchemy~=1.3` as dependency?

 I downloaded the `trino-0.308.0.tar.gz (23.0 kB)` from https://pypi.org/project/trino/#files 
 
 Here's what the package includes.
 
 ```
 $ tree
.
├── LICENSE
├── PKG-INFO
├── README.md
├── setup.cfg
├── setup.py
├── trino
│   ├── __init__.py
│   ├── auth.py
│   ├── client.py
│   ├── constants.py
│   ├── dbapi.py
│   ├── exceptions.py
│   ├── logging.py
│   └── transaction.py
└── trino.egg-info
    ├── PKG-INFO
    ├── SOURCES.txt
    ├── dependency_links.txt
    ├── entry_points.txt
    ├── requires.txt
    └── top_level.txt

2 directories, 19 files
```

**Comment by hashhar** [comment]
That's how extras work with setuptools and is expected AFAIK.

We are working on adding documentation and more integration tests for sqlalchemy dialect. I think once documented there should be less confusion.

**Comment by hashhar** [comment]
Ah, good point. Looks like setuptools doesn't have the sqlalchemy module registered so it's not part of the distribution.

Thanks for raising this. I think adding `trino.sqlachemy` to setup.py is all that's required.

cc: @dungdm93

**Comment by dungdm93** [comment]
See #136
