### ISSUE TITLE
newconnectionerror

### ISSUE THREAD

**Issue by JeevansSP** [trinodb/trino-python-client#140]
```

import trino
conn = trino.dbapi.connect(
    host='127.0.0.1',
    port=8080
  
)
cur = conn.cursor()
cur.execute('SELECT * FROM system.runtime.nodes')
rows = cur.fetchall()
```

Hello I'm trying to run this but I keep getting this error
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002EC58FCDA00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))    
does anyone know why would I be facing this issue?

**Comment by ebyhr** [comment]
Can you connect to the Trino server using CLI for separating issues? 
https://trino.io/download.html

**Comment by JeevansSP** [comment]
> Can you connect to the Trino server using CLI for separating issues? https://trino.io/download.html

hello , so I tried running the CLI and I had to create a .bat file and then run it, I got the CLI to open but I'm unable to run any commands
![image](https://user-images.githubusercontent.com/81505255/146717155-c0ff6ce6-0391-4088-a0bd-f2fdd1c8e8a3.png)
when I write a command and press enter it just goes to the next line , please help

**Comment by ebyhr** [comment]
Please execute `SELECT 1;`  with new tab.

**Comment by JeevansSP** [comment]
> Please execute `SELECT 1;` with new tab.

![image](https://user-images.githubusercontent.com/81505255/146717821-f86f3618-0340-490c-b50a-1bd176274eb5.png)
hey thanks but i get this error now

**Comment by ebyhr** [comment]
Is your Trino server running in a same machine with 8080 port?

**Comment by JeevansSP** [comment]
> Is your Trino server running in a same machine with 8080 port?

do you mean is my application running with a 8080 port then yes Its running on my laptop, if that isn't what you meant, im sorry can you elaborate a little?

**Comment by JeevansSP** [comment]
> Is your Trino server running in a same machine with 8080 port?

![image](https://user-images.githubusercontent.com/81505255/146718624-a41d8c25-8321-4f4f-a2a0-d3db453a98f2.png)
hold up this is what i found about my port

**Comment by JeevansSP** [comment]
> Is your Trino server running in a same machine with 8080 port?

![image](https://user-images.githubusercontent.com/81505255/146718813-562b4b9e-36f2-4640-a4c7-5c684ebd6652.png)

**Comment by ebyhr** [comment]
Please share command and log when you started Trino server.

**Comment by JeevansSP** [comment]
> Please share command and log when you started Trino server.

im really sorry but i do not know how to check that , i created a .bat file and put this inside it 'java -jar trino.jar' and then run it , that's how i got the trino .jar file to open, how do i check the logs

**Comment by ebyhr** [comment]
`trino.jar` is a client program for connecting to Trino server. You haven't yet started Trino server?

**Comment by JeevansSP** [comment]
> `trino.jar` is a client program for connecting to Trino server. You haven't yet started Trino server?
i guess not, I only downloaded the cli and started to run it

**Comment by JeevansSP** [comment]
> `trino.jar` is a client program for connecting to Trino server. You haven't yet started Trino server?

just started to download  'trino-server-366.tar.gz'

**Comment by JeevansSP** [comment]
> `trino.jar` is a client program for connecting to Trino server. You haven't yet started Trino server?

I'm sorry but how do I unpack it

**Comment by ebyhr** [comment]
You can use WinZip or something to open tar.gz in Windows.

**Comment by JeevansSP** [comment]
> `trino.jar` is a client program for connecting to Trino server. You haven't yet started Trino server?

hello, I downloaded and unpacked it,  how do I start the server?

**Comment by JeevansSP** [comment]
![image](https://user-images.githubusercontent.com/81505255/146722361-f43ee39a-0441-4b7c-9a2b-592b3127a176.png)

**Comment by ebyhr** [comment]
I'm not sure about your goal, but I would recommend trying WSL2, docker or Linux VM if you are using Windows. 
https://hub.docker.com/r/trinodb/trino

**Comment by JeevansSP** [comment]
> I'm not sure about your goal, but I would recommend trying WSL2, docker or Linux VM if you are using Windows. https://hub.docker.com/r/trinodb/trino

my goal is to connect to Azure data lake storage its a ADFS type storage system (blob storage) for querying files , so once I figure out docker I will use the python trino library and connect

**Comment by ebyhr** [comment]
Got it. Let me close this issue because you need to setup Trino server first. Please ask questions in the community Slack if you need help during installation. https://trino.io/slack.html

**Comment by JeevansSP** [comment]
> Got it. Let me close this issue because you need to setup Trino server first. Please ask questions in the community Slack if you need help during installation. https://trino.io/slack.html

a small doubt, to deploy the server we use docker right? and only once it is deployed i can continue using my python trino library?
