### ISSUE TITLE
query information_schema with existing schema name returns columns non-exist error

### ISSUE THREAD

**Issue by therealJacobWu** [trinodb/trino-python-client#141]
Hi, I got the following error while running the query
`trino_cursor.execute('''SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" =uip_chenhao_db''')
`
ERROR:
`---------------------------------------------------------------------------
TrinoUserError                            Traceback (most recent call last)
/tmp/ipykernel_45823/3428439138.py in <module>
      1 trino_cursor.execute('''SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" =uip_chenhao_db AND "table_name" =chenhao_test_pandastotrino''')
----> 2 data = trino_cursor.fetchall()

/opt/python3common/lib/python3.7/site-packages/trino/dbapi.py in fetchall(self)
    455 
    456     def fetchall(self) -> List[List[Any]]:
--> 457         return list(self.genall())
    458 
    459     def cancel(self):

/opt/python3common/lib/python3.7/site-packages/trino/client.py in __iter__(self)
    441         # Subsequent fetches from GET requests until next_uri is empty.
    442         while not self._query.finished:
--> 443             rows = self._query.fetch()
    444             for row in rows:
    445                 self._rownumber += 1

/opt/python3common/lib/python3.7/site-packages/trino/client.py in fetch(self)
    518         """Continue fetching data for the current query_id"""
    519         response = self._request.get(self._request.next_uri)
--> 520         status = self._request.process(response)
    521         if status.columns:
    522             self._columns = status.columns

/opt/python3common/lib/python3.7/site-packages/trino/client.py in process(self, http_response)
    388         logger.debug("HTTP %s: %s", http_response.status_code, response)
    389         if "error" in response:
--> 390             raise self._process_error(response["error"], response.get("id"))
    391 
    392         if constants.HEADER_CLEAR_SESSION in http_response.headers:

TrinoUserError: TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 1:78: Column 'uip_chenhao_db' cannot be resolved", query_id=20211213_230106_00075_bhywy)`

And I can verify the corresponding schema entry exist in the table_schema column:
`trino_cursor.execute('''SELECT * FROM "information_schema"."tables"''')
column_names = [desc[0] for desc in trino_cursor.description]
df = pd.DataFrame(trino_cursor.fetchall(), columns=column_names)
'uip_chenhao_db' in df.table_schema.values`

**Comment by therealJacobWu** [comment]
Basically, I am trying to run the query in this line [,](https://github.com/dungdm93/sqlalchemy-trino/blob/ad875448597e71eee2f3b6a64e2588a6889b64aa/sqlalchemy_trino/dialect.py#L243) but it failed with the above error.

**Comment by ebyhr** [comment]
tip: You can use three backquotes for formatting code. 
https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by ebyhr** [comment]
Please make sure whether it's Python client issue or server side issue.

**Comment by hashhar** [comment]
Looking at the query again it seems you didn't quote the predicate.

```diff
-trino_cursor.execute('''SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" =uip_chenhao_db''') 
+trino_cursor.execute('''SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" = "uip_chenhao_db"''') 
```

See the diff. The value needs to be quoted otherwise it's resolved as a column name.

**Comment by therealJacobWu** [comment]
> Looking at the query again it seems you didn't quote the predicate.
> 
> ```diff
> -trino_cursor.execute('''SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" =uip_chenhao_db''') 
> +trino_cursor.execute('''SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" = "uip_chenhao_db"''') 
> ```
> 
> See the diff. The value needs to be quoted otherwise it's resolved as a column name.

It still failed with the double quote:
```
---------------------------------------------------------------------------
TrinoUserError                            Traceback (most recent call last)
/tmp/ipykernel_45802/4069212501.py in <module>
      1 trino_cursor.execute('''SELECT * FROM "information_schema"."tables" WHERE "table_schema" = "uip_chenhao_db"''')
----> 2 data = trino_cursor.fetchall()

/opt/python3common/lib/python3.7/site-packages/trino/dbapi.py in fetchall(self)
    455 
    456     def fetchall(self) -> List[List[Any]]:
--> 457         return list(self.genall())
    458 
    459     def cancel(self):

/opt/python3common/lib/python3.7/site-packages/trino/client.py in __iter__(self)
    441         # Subsequent fetches from GET requests until next_uri is empty.
    442         while not self._query.finished:
--> 443             rows = self._query.fetch()
    444             for row in rows:
    445                 self._rownumber += 1

/opt/python3common/lib/python3.7/site-packages/trino/client.py in fetch(self)
    518         """Continue fetching data for the current query_id"""
    519         response = self._request.get(self._request.next_uri)
--> 520         status = self._request.process(response)
    521         if status.columns:
    522             self._columns = status.columns

/opt/python3common/lib/python3.7/site-packages/trino/client.py in process(self, http_response)
    388         logger.debug("HTTP %s: %s", http_response.status_code, response)
    389         if "error" in response:
--> 390             raise self._process_error(response["error"], response.get("id"))
    391 
    392         if constants.HEADER_CLEAR_SESSION in http_response.headers:

TrinoUserError: TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 1:68: Column 'uip_chenhao_db' cannot be resolved", query_id=20211214_171018_00001_bhywy)
```

**Comment by therealJacobWu** [comment]
> Sorry for my mistake. The literal value should be single quoted, not double quoted.
> 
> ```diff
> -trino_cursor.execute('''SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" =uip_chenhao_db''') 
> +trino_cursor.execute('''SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" = 'uip_chenhao_db' ''') 
> ```

Thanks, this does solve the issue.
