### ISSUE TITLE
how to connect to hive using this library

### ISSUE THREAD

**Issue by JeevansSP** [trinodb/trino-python-client#143]
so i have the trino server running on docker and I was wondering how do I connect to Azure datalake storage, it has a ID and password so I tried , this
```python
import trino
conn = trino.dbapi.connect(
    host='coordinator url',
    port=8443,
    user='the-user',
    catalog='the-catalog',
    schema='the-schema',
    http_scheme='https',
    auth=trino.auth.BasicAuthentication("principal id", "password"),
)
cur = conn.cursor()
cur.execute('SELECT * FROM system.runtime.nodes')
rows = cur.fetchall()
```

but it gave me an error saying 
**requests.exceptions.ConnectionError: HTTPSConnectionPool(host='coordinator%20url', port=8443): Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000012D1CFBBCA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))**

but when I run 
```python
import trino
conn = trino.dbapi.connect(
    host='localhost',
    port=8080,
    user='the-user',
    catalog='the-catalog',
    schema='the-schema',
)
cur = conn.cursor()
cur.execute('SELECT * FROM system.runtime.nodes')
rows = cur.fetchall()
```

it works perfectly fine
so after reading for a bit I found out we need to use hive connector to connect to ADLS
 https://trino.io/docs/current/connector/hive-azure.html
so how do I connect to hive?

**Comment by ebyhr** [comment]
This issue unrelates to Python client. Please post a question in the community Slack or Trino's GitHub discussions. 
Slack: https://trino.io/slack.html
GitHub discussions https://github.com/trinodb/trino/discussions/new
