### ISSUE TITLE
Skip TLS verify when using https

### ISSUE THREAD

**Issue by mapshen** [trinodb/trino-python-client#144]
Is there a way to configure this? This is equivalent to `--insecure` supported by the [Trino CLI](https://trino.io/docs/current/installation/cli.html).

**Comment by ebyhr** [comment]
Could you try `verify=False` in `trino.dbapi.connect()`?

**Comment by mapshen** [comment]
Ah someone fixed it two months ago: https://github.com/trinodb/trino-python-client/commit/9e73d218f97ad6a0f6f9a19893314c580c333df7.

Thanks @ebyhr !
