### ISSUE TITLE
USE catalog.schema not honored

### ISSUE THREAD

**Issue by cccs-jc** [trinodb/trino-python-client#153]
The connection can be created with a catalog and schema argument. However I would have expected that the SQL USE statement would also switch between catalogs and schemas. Here's an example
```
import trino
conn = trino.dbapi.connect(
                host="localhost",
                port=8080,
                auth=None,
                user='the-user',
                http_scheme="http")
cur = conn.cursor()

# this works fine since table is fully qualified
cur.execute("select * from tpch.tiny.orders")
results = cur.fetchmany(10)
print(results)

# The USE statement to switch schema
cur.execute("use tpch.tiny")

# Query will fail because the USE statement is not honored
cur.execute("select * from orders")
results = cur.fetchmany(10)
print(results)
```

**Comment by hashhar** [comment]
I think this is a side-effect of the fact that today the protocol requires us to call cursor.fetch to actually run the query.

Maybe we should think of some way to decouple query execution from result retreival?

**Comment by cccs-jc** [comment]
I don't know the innards of trino python however as a user I would expect the USE statement to work.
