### ISSUE TITLE
Trino - OAUTH Error

### ISSUE THREAD

**Issue by gowthamprabhu** [trinodb/trino-python-client#164]
Getting the below error when trying to connect to Trino with OAUTH using Python.

TypeError: set_http_session() missing 1 required positional argument: 'http_session'

conn = trino.dbapi.connect(
    host='<<hostname>>',
    user='<<username>>',
    catalog='catalogue',
    schema='test_schema',
    port=8443, 
    http_scheme='https',
    auth=OAuth2Authentication 
)
cur = conn.cursor()

Hostname, username are replaced with actual values.

**Comment by ebyhr** [comment]
Let me close as answered. Please feel free to reopen if necessary.
