### ISSUE TITLE
SqlAlchemy Warning: SQL compilation caching

### ISSUE THREAD

**Issue by DeanLa** [trinodb/trino-python-client#171]
SqlAlchemy raises a warning

```sql
SAWarning: Dialect trino:rest will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
res = connection.execute(sql.text(query))
```

Happens on version `0.312.0` with `sqlalchemy>=1.4`

**Comment by DeanLa** [comment]
On a local branch I added
`supports_statement_cache = False` as class attr in `trino/sqlalchemy/dialect.py:TrinoDialect`.

It solved the warning. I wasn't sure whether to set this to `True` due to the warning "set this attribute to True after appropriate development and testing ".

Should I submit a pull request? (first submission)

**Comment by ebyhr** [comment]
@DeanLa Disabling the flag looks good to me. Could you submit both [CLA](https://github.com/trinodb/cla) and PR? 

cc: @dungdm93 @hashhar

**Comment by DeanLa** [comment]
Submitted SLA via email.
Submitted pull request #172
