### ISSUE TITLE
Proxy Trino Server Url Throws Error

### ISSUE THREAD

**Issue by sthakur84** [trinodb/trino-python-client#178]
def new_get_url(self, path) -> str:
    urlRet="{protocol}://{host}:{port}/api/kpd/siae/fsconsumermanifest/v1r/{path}".format(
     protocol=self._http_scheme, host=self._host, port=self._port, path=path
     )
    print(f'url returned is {urlRet}')
    return urlRet
def new_statement_url(self) -> str:
    return self.get_url(constants.URL_STATEMENT_PATH)
db_conn = trino.dbapi.connect(
    host='apiservice-bus-dev.kp.org',
    port=2005,
    user='***',
    catalog='system',
    schema='information_schema',
    http_scheme='https',
    http_headers={"envlbl":"trino","extraCredentials": "***"},
    auth=trino.auth.BasicAuthentication("****", "*****")
)
db_conn._http_session.cert = (crtPath,crtKeyPath)
db_conn._http_session.verify = pemPath
db_conn._http_session.get_url = new_get_url
db_conn._http_session.statement_url = new_statement_url

Throws below error with proxy url : HttpError: error 404: b'{"fault":{"faultstring":"Unable to identify proxy for host: secure and url: \\/v1\\/statement","detail":{"errorcode":"messaging.adaptors.http.flow.ApplicationNotFound"}}}'

**Comment by hashhar** [comment]
That error is coming from your proxy server - so it's something that whoever manages that for you would be able to help with.

I'm closing but feel free to reopen in case you learn more.
