### ISSUE TITLE
Add support for pyformat paramstyle

### ISSUE THREAD

**Issue by quickcoffee** [trinodb/trino-python-client#192]
Currently the trino python client does not support the [pyformat parameter style](https://peps.python.org/pep-0249/#paramstyle).  
Support for this paramstyle would allow to specify the parameters via a dict and use parameters in more complex queries where multiple parameters are defined, while maintaining a high code readability.  
See the [PyHive](https://github.com/dropbox/PyHive) implementation: https://github.com/dropbox/PyHive/commit/d6e7140d366cc37d01af0d8308e7739d090d73ef

**Comment by mdesmet** [comment]
Currently the parameters are interpolated using [the `PREPARE` and `EXECUTE` statements](https://trino.io/docs/current/sql/execute.html). The parameters are sent to the server using HTTP headers.

Using pyformat would mean doing the interpolation on the clientside and would result in just one in the HTTP body.

The relevant code is here:

https://github.com/trinodb/trino-python-client/blob/951ad82b7a7571c99dddf4e35f66fb403f052c11/trino/dbapi.py#L452-L480

@quickcoffee: Are you willing to do a PR to implement this?

**Comment by hashhar** [comment]
Client side interpolation doesn't seem a good idea because then the client will end up playing catch up with what the server supports. While the end goal is useful (more readable Python code with complex queries) the solution has a cost.

I'd argue that people should use something higher level like SQLAlchemy if they need more choice.

**Comment by quickcoffee** [comment]
@mdesmet I could create a PR, if you are willing to use client side interpolation, which we should figure out first.  

Regarding the comment from @hashhar: I understand that there is a cost. Maybe the python client is then not the right place to support `pyformat`, but rather have a separate SQLAlchemy dialect package?  
As I understand you need to provide SQLAlchemy with a [dialect](https://docs.sqlalchemy.org/en/14/core/internals.html#sqlalchemy.engine.Dialect), which is currently [registered](https://github.com/trinodb/trino-python-client/blob/748d197e5b8f959ef8c81a90029633d102430cf6/trino/sqlalchemy/__init__.py#L14) by the trino python client. As the python client does not support `pyformat`, another backend needs to be used (eg. [PyHive](https://github.com/dropbox/PyHive)), but I would rather use an official trino backend than an unsupported package

**Comment by hashhar** [comment]
We don't intend to provide multiple options for `paramstyle` in the near future at-least. Closing for now.
