### ISSUE TITLE
Add a configurable sleep to query status polling

### ISSUE THREAD

**Issue by nickwareing** [trinodb/trino-python-client#193]
Currently, the client [loops continuously whilst a query is running,](https://github.com/trinodb/trino-python-client/blob/a5ee23e7f33ddf1c89abf27e0e8e912097527b73/trino/client.py#L510-L512) sending `GET` fetch requests. For clients issuing a high volume of long running queries (ETL), these requests add unnecessary load to the Trino cluster and any intermediary proxying systems (`lyft-gateway` for example).

Can we add a configurable sleep (default to 0 to preserve current behaviour) to the fetch logic?

**Comment by dain** [comment]
This is how the Trino protocol is designed to work.  The server assumes that clients are dumb and delays responses to force request waits.

**Comment by nickwareing** [comment]
Closing, based on @dain's explanation.
