### ISSUE TITLE
Configure `experimental_python_types` through `connect`.

### ISSUE THREAD

**Issue by tkorvola** [trinodb/trino-python-client#197]
Currently `connection.cursor(experimental_python_types=True)` is needed to enable support for, e.g., timestamps.  It is against DBAPI for `cursor` to take parameters and SQLAlchemy does not seem to provide any means for passing them. I'd suggest moving the flag to `connect`, where database dependent parameters are allowed; in SQLAlchemy you'd pass them as `connect_args` to `create_engine`.

**Comment by mdesmet** [comment]
HI @tkorvola, thanks for raising this issue.

Could you refer me to where you found that this is against DBAPI. I don't seem to find that on https://peps.python.org/pep-0249/#cursor-objects

Could you maybe rename the issue to "Configure `experimental_python_types` parameter through the Connection object"? That way we are backwards compatible and also support the SQLAlchemy use case.

**Comment by tkorvola** [comment]
You can of course keep the current optional parameter of `cursor`. [It is just not part of DBAPI](https://peps.python.org/pep-0249/#cursor), thus frameworks built on DBAPI can't be expected to support it. In contrast, [they can be expected to support passing arbitrary parameters to `connect`](https://peps.python.org/pep-0249/#connect).
