### ISSUE TITLE
printing http response as info in client.py cancel()

### ISSUE THREAD

**Issue by EugeneChung** [trinodb/trino-python-client#215]
Hi all.

```
[INFO|client.py:807] 2022-08-11 10:01:04,392 > <Response [204]>
```

https://github.com/trinodb/trino-python-client/blame/e26027375326a1e0fc8a472d242af75b4e6049bc/trino/client.py#L807

Is it intended or should it be debug level?

**Comment by hashhar** [comment]
It doesn't seem to be intended. Would you like to send a PR?

**Comment by EugeneChung** [comment]
@hashhar Okay~

**Comment by EugeneChung** [comment]
FYI, it happens because of #195 .
Calling sqlalchemy result.scalar() from trino/sqlalchemy/dialect.py#_get_server_version_info() closes the cursor which is not finished, and it causes cancelling of `SELECT version()` query.

**Comment by guyco33** [comment]
> FYI, it happens because of #195 . [Calling sqlalchemy result.scalar() from trino/sqlalchemy/dialect.py#_get_server_version_info()](https://github.com/trinodb/trino-python-client/blob/1cdad16abc0031ad69cb72081026dd1d0b105ca8/trino/sqlalchemy/dialect.py#L320) closes the cursor which is not finished, and it causes cancelling of `SELECT version()` query.

@hashhar @EugeneChung 
https://github.com/trinodb/trino-python-client/pull/210 fixes it
