### ISSUE TITLE
Trino Client prompting for authentication at every Cursor created when using OAuth2Authentication

### ISSUE THREAD

**Issue by IceS2** [trinodb/trino-python-client#224]
Hello! I'm using the client to query [Starburst](https://www.starburst.io/).

I've been trying to understand how the Cache works for OAuth2Authentication since it's prompting for authentication at every cursor created.
I imagine it'd make sense to prompt for it at each connection created but not at every cursor, if not closing the previous opened connection.

I've got that error with the following code:
```
import trino

conn = trino.dbapi.connect(
            host=<HOST>,
            port=443,
            user=<USER>,
            http_scheme='https',
            auth=trino.auth.OAuth2Authentication()
        )

cur = conn.cursor()
cur.execute('SHOW CATALOGS')

cur = conn.cursor()
cur.execute('SHOW SCHEMAS IN hive')
```

![image](https://user-images.githubusercontent.com/4912399/185358517-23240ec1-c035-4de0-8dfb-04a44cccb870.png)

If I reuse the same cursor this behavior doesn't happen and I don't need to authenticate multiple times.

**Comment by IceS2** [comment]
I'm not sure I understand the first part of your answer. The URL is launched on the webbrowser (I actually get a new tab with the authentication taking place). Isn't that right or am I missing something?

For the cache part I thought InMemory default one would work, but I'll check the custom cache solution!

**Comment by mdesmet** [comment]
> I'm not sure I understand the first part of your answer. The URL is launched on the webbrowser (I actually get a new tab with the authentication taking place). Isn't that right or am I missing something?

Good to hear that the webbrowser works, I assume you run the notebook server locally then. It would not work if it's on a remote server that doesn't have a webbrowser.

> For the cache part I thought InMemory default one would work, but I'll check the custom cache solution!

You might be right about this as the Python kernel in Jupyter must be kept alive including the inMemory cache. I will give it a try myself over the weekend.

**Comment by IceS2** [comment]
You're absolutely right!
I finally deployed a Notebook Service on EKS and it's stuck due to the webbrowser. I'll deal with that and then try to investigate the inMemory cache as well.

I assume that I should be able to reuse the connection without having to authenticate multiple times, right?

Thanks (=

**Comment by IceS2** [comment]
Curiously enough I couldn't find what the issue behind it was. Eventually at the production environment (Jupyterhub on EKS) everything worked as expected, being able to reuse the connection and create new cursors without any needs to keep authenticating at every new cursor.

Unless you'd like to debug more to understand why my original setup was having this issue we can close the issue (=

**Comment by hashhar** [comment]
We now have a built-in token cache which should reuse OAuth tokens as long as you connect using same user and to same Trino URI.
