### ISSUE TITLE
Asyncio-compatible version

### ISSUE THREAD

**Issue by samuelscortez0616** [trinodb/trino-python-client#3]
Hi,

I was wondering if it would be possible to have a version that is compatible with `asyncio` that can be pooled with other tasks. This would really help improve performance as I often to run queries both on Presto and Postgresql connections. Thank you!

**Comment by ggreg** [comment]
Yes I was thinking of getting rid of Python2 support and when moving to Python3-only, add support for asyncio.

**Comment by mvanderlee** [comment]
It's not PR ready, but I created an asyncio fork here: https://github.com/mvanderlee/trino-python-client/tree/py3-async

**Comment by mvanderlee** [comment]
I've cleaned it up, got the builds passing and deployed it as `aiotrino` on pypi. 
Based on the amount of work required, I think it makes sense as a second package instead of integrating Asyncio into the current client. 
I'd gladly transfer `aiotrino` to the trinodb community if requested.

**Comment by ShH01m3s** [comment]
Hi! Thanks a lot for the `aiotrino` module! :) 
Do you plan to add OAuth2Authentication authentication support to the backlog?

**Comment by mvanderlee** [comment]
@ShH01m3s I am not planning on it. I have split it to it's own repo, so feel free to submit a PR: https://github.com/mvanderlee/aiotrino

**Comment by pw24** [comment]
> @ShH01m3s I am not planning on it. I have split it to it's own repo, so feel free to submit a PR: https://github.com/mvanderlee/aiotrino

Hi. I've tried out the library as to benefit from making multiple requests concurrently from a python client perspective. After doing so, I just added a `JWTAuthentication` similar to the one used in this trino package so that a client can just pass in their jwt tokens for requests. @ShH01m3s, this likely addresses your request as well?

Just need a PR please ([pull request](https://github.com/mvanderlee/aiotrino/pull/1)).

**Comment by hashhar** [comment]
There are no plans to add asyncio compatible client for now. Closing for now. We can revisit this in future.

For now there is an `aiotrino` client available outside of the main project for people who want to try out asyncio.
