### ISSUE TITLE
Enable experimental_python_types by default and change the name

### ISSUE THREAD

**Issue by damian3031** [trinodb/trino-python-client#305]
### Describe the feature

Enable `experimental_python_types` by default.
Change this parameter name to `legacy_python_types`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by hashhar** [comment]
`legacy_python_types` might not be descriptive enough. What about `raw_results`/`untyped_results`?

**Comment by hashhar** [comment]
Also as a part of this we should make sure we document clearly the limitations of the new default and mention how to workaround them when needed.

**Comment by damian3031** [comment]
@hashhar If I understand correctly, logic behind utilising current passed parameter `experimental_python_types` is [here](https://github.com/trinodb/trino-python-client/blob/master/trino/client.py#L1137-L1139)

So if this parameter is `True`, then type mapping is performed.

So, after changing this parameter name to `raw_results`/`untyped_results`, setting `raw_results` to True would cause to perform mapping, shouldn't it be the opposite? 

Maybe we could name this parameter differently, instead of `raw_results`/`untyped_results` maybe sth like `typed_results`/`mapped_results`? and then by default `mapped_results` == True and mapping is performed?

Or maybe I could add negation [here](https://github.com/trinodb/trino-python-client/blob/master/trino/client.py#L1137) and then leave default value to False, so by default `raw_result` == False and mapping is performed?

**Comment by hashhar** [comment]
> setting raw_results to True would cause to perform mapping, shouldn't it be the opposite?

Yes. The name change also means the logic needs to be inverted.

> Or maybe I could add negation [here](https://github.com/trinodb/trino-python-client/blob/master/trino/client.py#L1137), rename to raw_result and leave default value to False, so by default raw_result == False and mapping is performed?

This seems good to me.

@hovaesco / @mdesmet any opinion?

**Comment by hovaesco** [comment]
Sounds good to me, I'm not in favour of `raw_results` name, `untyped_results` is better or maybe `legacy_untyped_results`?

**Comment by mdesmet** [comment]
untyped seems a little weird as the results are always typed. Maybe `legacy_primitive_types`?

**Comment by hashhar** [comment]
are the results typed or are they always string?

**Comment by mdesmet** [comment]
The api only returns `string` or `int`. Other types are explicitly mapped.
