### ISSUE TITLE
Disable prepared statements by default

### ISSUE THREAD

**Issue by damian3031** [trinodb/trino-python-client#306]
### Describe the feature

Disable prepared statements by default.
Exact approach and details about implementation could be discussed in the comments.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by damian3031** [comment]
In this draft PR #310 3 possible approaches of handling this issue were presented. All of them were thoroughly discussed. As a result, we decided that the best approach is nr 3 - transporting prepared statement parameters in the JSON body instead of the headers. It will fix biggiest issue here - hitting header limit size by query. Query will be still parsed by SQL parser on Trino side, as opposed to approach nr 2.

Due to the low priority and high complexity of this issue, it is currently on hold.

**Comment by aalbu** [comment]
@hashhar, can we close this issue?  Based on comments in the referenced PR, it seems like the the main problem it's attempting to address is the header size limitations for prepared statements.  At this point, we have a way to avoid passing prepared statement parameters in the header, but specifying `legacy_prepared_statements=False`.

**Comment by hashhar** [comment]
Yes, I think this is no longer as relevant because of EXECUTE IMMEDIATE.

We can revisit if there's still interest in this.
