### ISSUE TITLE
Add callproc to call stored procedures

### ISSUE THREAD

**Issue by mdesmet** [trinodb/trino-python-client#320]
### Describe the feature

DBAPI provides following method to call stored procedures.

> [.callproc](https://peps.python.org/pep-0249/#callproc)( procname [, parameters ] )
> (This method is optional since not all databases provide stored procedures. [[3]](https://peps.python.org/pep-0249/#id51))
> Call a stored database procedure with the given name. The sequence of parameters must contain one entry for each argument that the procedure expects. The result of the call is returned as modified copy of the input sequence. Input parameters are left untouched, output and input/output parameters replaced with possibly new values.
> 
> The procedure may also provide a result set as output. This must then be made available through the standard [.fetch*()](https://peps.python.org/pep-0249/#id24) methods.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by hashhar** [comment]
There are no stored procedures yet on the server side. Can you share more detail about how it might be used?

**Comment by mdesmet** [comment]
See https://trino.io/docs/current/sql/call.html

For example there exists a stored procedure to [register a table on Iceberg](https://trino.io/docs/current/connector/iceberg.html?highlight=iceberg#register-table).

**Comment by hashhar** [comment]
I don't think those are "stored procedures" regardless of what the docs say.

@martint / @dain Once/when SQL defined functions land do we expect to reuse the `CALL` statement to execute those?
I'd like to avoid a situation where we need to change what `callproc` does once SQL defined functions/SPs are available since it'd break user code.

**Comment by hashhar** [comment]
Closing since we don't have plans in this direction for now.

For `CALL <procedure>` syntax in Trino and invoking functions both we expect users to use the `execute` API for now.
