### ISSUE TITLE
Represent ROW types as dict instead of tuple

### ISSUE THREAD

**Issue by wliufle** [trinodb/trino-python-client#338]
### Describe the feature

Right now, fetchone or fetchall returns ROW type as a tuple of ROW values, leaving the field name out. 

Here's a simple example:

```
result = cur.execute("SELECT ARRAY[CAST(ROW(123, 'abc', true) AS ROW(v1 BIGINT, v2 VARCHAR, v3 BOOLEAN)), CAST(ROW(456, 'def', false) AS ROW(v1 BIGINT, v2 VARCHAR, v3 BOOLEAN))]")
cur.fetchone()


[(123, 'abc', True), (456, 'def', False)]
```

Even though the field names can be retrieved from cursor.description, the result looks different than from other clients, such as JDBC and trino-cli. It would make more sense to represent a ROW as a dict:

```
[{'v1': 123, 'v2': 'abc', 'v3': True}, {'v1': 456, 'v2': 'def', 'v3': False}]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hashhar** [comment]
For correct behavior it needs to be an ordered dict preserving the order returned by the server because if you use the dict to build another query then unless the ROW type has the fields in same order they won't be considered the same data type.

This enhancement makes sense in general but when being implemented the above point needs to be kept in mind.

**Comment by mdesmet** [comment]
Please have a look at following PR: https://github.com/trinodb/trino-python-client/pull/335

This aims at providing named tuples for the ROW data type if attribute information is available. Also note that ROWs also can return duplicate column names. eg `SELECT CAST(ROW(1, 2.0) AS ROW(x BIGINT, x DOUBLE))`.

**Comment by Raghav-254** [comment]
So from now onwards, the field names will also be displayed and instead of tuples, the return type would be dict?.
And when are you planning to release this enhancement?
And it will work for sqlalchemy as well right?

**Comment by mdesmet** [comment]
The return type will be still tuple but it will contain named attributes. It should work with sqlalchemy.

**Comment by Raghav-254** [comment]
Hi folks, can you please help me in one thing?
What could be the most efficient way to iterate over the NamedRowTuple which is there in this PR #335?
I have a usecase where I need access the values in the NamedRowTuple and do some processing over it.
