### ISSUE TITLE
Null values are getting converted to None

### ISSUE THREAD

**Issue by Raghav-254** [trinodb/trino-python-client#362]
### Expected behavior

Null values in the dataset should remain as null.

### Actual behavior

Null values are getting converted to None 

### Steps To Reproduce

You can take any dataset having null value, it will automatically get converted to None.
For instance refer the below process:
1. Create a table
`
CREATE TABLE IF NOT EXISTS null_data (
  c1 row(id VARCHAR, id1 VARCHAR),
  c2 VARCHAR
);
`
2. Insert values into the table
`
INSERT INTO null_data 
VALUES (ROW('a', 'b'), NULL);
`
`
INSERT INTO null_data 
VALUES (NULL, 'c');
`
3. Run the select query
`
select * from null_data
`

Expected output should have **NULL** values in it, but the **NULL** values got replaced by **None**.

### Operating System

NA

### Trino Python client version

0.322.0

### Trino Server version

NA

### Python version

5.10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hashhar** [comment]
If you want to retrieve results as strings you can disable the behaviour which maps results to Python type by enabling the legacy mode https://github.com/trinodb/trino-python-client#legacy-primitive-types.
