### ISSUE TITLE
JSON functionality

### ISSUE THREAD

**Issue by dwolfeu** [trinodb/trino-python-client#387]
### Describe the feature

Can the [standard JSON operations](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.JSON) such as `some_table.c.json_column['some key']` and `some_table.c.json_column[('key_1', 'key_2', 5, ..., 'key_n')]` be implemented?

### Describe alternatives you've considered

[I sought the advice of the community.](https://stackoverflow.com/questions/76613959/json-parsing-with-trino-and-sqlalchemy-orm/)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hashhar** [comment]
Fixed via https://github.com/trinodb/trino-python-client/pull/425
