### ISSUE TITLE
Make code Python3 only

### ISSUE THREAD

**Issue by ggreg** [trinodb/trino-python-client#4]

**Comment by joshthoward** [comment]
@ggreg completely agree with you...

For anyone else looking at this, the Python Software Foundation has [deprecated](https://www.python.org/doc/sunset-python-2/) Python 2.

**Comment by findepi** [comment]
Well... it was deprecated long ago. 
What matters though are facts on the ground.
Sadly, I do not know of a good way to know whether there are users still on Python 2 and how many.

**Comment by findepi** [comment]
@joshthoward maybe https://packaging.python.org/guides/analyzing-pypi-package-downloads/ could help, and https://packaging.python.org/guides/analyzing-pypi-package-downloads/#python-versions-over-time in particular?
the `trino` PyPI package is very new, but we could check for `presto-client` there.

**Comment by joshthoward** [comment]
@findepi that would be an analytical way to validate that there are few Python 2 users, but it seems like a moot point given that the version is deprecated and also not supported by basic analytical libraries like Pandas or Numpy.

**Comment by nineinchnick** [comment]
It's not only deprecated but actually not supported anymore.

**Comment by findepi** [comment]
I agree with you that it would be great to drop Python 2 compatibility.
I am not convinced checking Python 2 deprecation status is sufficient for that. 

Java 8 is EOL'd and not supported (unless you pay $$$), but we don't feel comfortable dropping Java 8 support from JDBC or CLI tools.
Python 2 was "deprecated" like 10 years ago (or am i wrong here?).

to be clear: i am not afraid of forcing one straggler to upgrade. I just want that we make sure we don't leave some % of users in a bad situation.

**Comment by yuokada** [comment]
I believe pyupgrade is useful for this issue.
https://github.com/asottile/pyupgrade

**Comment by joshthoward** [comment]
@findepi Fair enough. The BigQuery link you posted was surprisingly easy to follow.  

Here are the results for the `presto-client` package over the last 6 months...

Query:
```
#standardSQL
SELECT
  REGEXP_EXTRACT(details.python, r"[0-9]+\.[0-9]+") AS python_version,
  COUNT(*) AS num_downloads,
FROM `the-psf.pypi.file_downloads`
WHERE
  file.project = 'presto-client'
  -- Only query the last 6 months of history
  AND DATE(timestamp)
    BETWEEN DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH), MONTH)
    AND CURRENT_DATE()
GROUP BY `python_version`
ORDER BY `num_downloads` DESC
```

Results:
| python_version | num_downloads |
| ----------- | ----------- |	
| 3.6 | 24655 |	
| 3.7 | 22170 |	
| 3.8 | 8138 |	
| 3.5 | 2955 |
| null | 2916 |	
| 3.9 | 1354 |
| 2.7 | 546 |
| 3.4 | 1 |

So Python 2 counts for 0.8% of all downloads for the old package.

Similarly, here are the results for Trino package...

Query: 
```
#standardSQL
SELECT
  REGEXP_EXTRACT(details.python, r"[0-9]+\.[0-9]+") AS python_version,
  COUNT(*) AS num_downloads,
FROM `the-psf.pypi.file_downloads`
WHERE
  file.project = 'trino'
  -- Only query the last 6 months of history
  AND DATE(timestamp)
    BETWEEN DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH), MONTH)
    AND CURRENT_DATE()
GROUP BY `python_version`
ORDER BY `num_downloads` DESC
``` 

Results: 
| python_version | num_downloads |
| ----------- | ----------- |	
| null | 843 |  
| 3.7 | 119 |  
| 3.6 | 36 |  
| 3.8 | 30 |  
| 2.7 | 15 |  
| 3.9 | 9 |  
| 3.5 | 7 |

Python 2 counts for 1.4% of all downloads for the new package.

Last but not least, let's make sure that Python2 installs are trending downward... 

Query: 

```
#standardSQL
SELECT
  COUNT(*) AS num_downloads,
  DATE_TRUNC(DATE(timestamp), MONTH) AS `month`
FROM `the-psf.pypi.file_downloads`
WHERE
  file.project = 'presto-client'
  AND REGEXP_EXTRACT(details.python, r"[0-9]+\.[0-9]+") = '2.7'
  -- Only query the last 6 months of history
  AND DATE(timestamp)
    BETWEEN DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH), MONTH)
    AND CURRENT_DATE()
GROUP BY `month`
ORDER BY `month` DESC
```

Results:
| count | month |
| ----------- | ----------- |	
| 44 | 2021-01-01 |  
| 69 | 2020-12-01 |  
| 75 | 2020-11-01 |  
| 87 | 2020-10-01 |  
| 88 | 2020-09-01 |  
| 109 | 2020-08-01 |  
| 74 | 2020-07-01 |

Thoughts?

**Comment by electrum** [comment]
Since there are concrete benefits to dropping supporting such cleaner code and static type checking (#69), I suggest we do a final release with Python 2 support (assuming there have been changes to warrant a release) and then drop it.

Are there any best practices or examples from other libraries? Do we need to explicitly signal that it only supports Python 3, so that anyone accidentally using the new version doesn’t get a syntax error (or whatever would happen)?

**Comment by joshthoward** [comment]
@electrum You are right, it would surface as a syntax error. You could add something like this to the `__init__.py` method to alert the user. 

```python
import sys
if sys.version_info.major < 3:
    raise UserError("Must be using Python 3")
```

**Comment by findepi** [comment]
@joshthoward thanks for taking the time to analyze the data and provide the summary in concise & informative way.
The 0.8% is not zero, but it's the threshold where It's better for the project and the community to move forward.

@electrum i don't think there is anything feature-wise to release, so unless we need to somehow prepare the "last py 2" release, we're good.

@joshthoward @pgagnon 
PyPI has the compatibility information 
https://github.com/trinodb/trino-python-client/blob/06d0f1365392ba97ceb44e27ef8c674bee55f646/setup.py#L63-L66
is it used in any way, e.g. by `pip install`?

Good idea to add  `sys.version_info`-based check too.

**Comment by pgagnon** [comment]
> is it used in any way, e.g. by `pip install`?

@findepi AFAIK no; these are only used for classification purposes. pip honors [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) though.

**Comment by findepi** [comment]
> pip honors [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) though.

This looks like what we need, thanks!

**Comment by electrum** [comment]
Do we have agreement now, such that we can move forward with @yuokada’s #70?

**Comment by findepi** [comment]
I think i should have expressed this more clearly. -- @electrum  I do agree to move forward with this.

**Comment by findepi** [comment]
I tested out `python_requires='>=3'` on a side project and it apparently makes pip _ignore_ versions not satisfying requirements.
if we go this route, `pip install trino` run with Python 2 will install latest trino version that supports Python 2, without notifying the user they are not installing the latest and greatest version.
The behavior that I would prefer is that the installation _fails_ and the user needs to explicitly opt in to use an old (and thus unmaintained) version.
For this we would probably need to https://github.com/trinodb/trino-python-client/issues/4#issuecomment-761712042 instead.

**Comment by pgagnon** [comment]
> For this we would probably need to [#4 (comment)](https://github.com/trinodb/trino-python-client/issues/4#issuecomment-761712042) instead.

It would probably be friendlier to perform this check in the `setup.py` files instead of in `__init__.py`, though. This way the user will be notified at install time instead of getting an unpleasant surprise at runtime.

**Comment by findepi** [comment]
@pgagnon good point! Does it depend on whether we build a wheel package? or is setup.py always used?

**Comment by pgagnon** [comment]
@findepi No, wheels bypass `setup.py`, but we can simply avoid distributing python 2 variants and it would fallback to a source install.
