### ISSUE TITLE
Support SQLAlchemy 2.x

### ISSUE THREAD

**Issue by hongbo-miao** [trinodb/trino-python-client#407]
### Describe the feature

In the readme, it says

> trino.sqlalchemy is compatible with the latest 1.3.x and 1.4.x SQLAlchemy versions at the time of release of a particular version of the client.

It would be great to support SQLAlchemy 2.x, thanks! ☺️

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hovaesco** [comment]
It's already being tested with SQLAlchemy 2.0.x, I will update the README.

**Comment by hashhar** [comment]
Fixed in https://github.com/trinodb/trino-python-client/pull/409
