### ISSUE TITLE
[Feature] add support pyarrow flight connector 

### ISSUE THREAD

**Issue by YuriyGavrilov** [trinodb/trino-python-client#416]
### Describe the feature

just add the arrow flight RPC connector 
https://arrow.apache.org/docs/python/generated/pyarrow.flight.connect.html
This is modern solution to ingest large amount of data.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mosabua** [comment]
What do you envision as the benefit of this? 

If the python client connects to a flight server to get the data and runs on a client workstation and then submits the data to trino then the workstation is a bottleneck.

**Comment by YuriyGavrilov** [comment]
@mosabua It seems I was a little fascinated by the speed of technology and wrote down the idea in the wrong place :) 
Of course, you are right that sending data back to trino does not make much sense from a workstation and it is the server that must support the flight server, and Python already has enough libraries for connection. so close it.
