### ISSUE TITLE
Support date and time functions

### ISSUE THREAD

**Issue by tkasuz** [trinodb/trino-python-client#422]
### Describe the feature

It would be really helpful to support cusotm functions especially date and time functions as SQLAlchemy dialect. I would like to add functions like the following under `trino/sqlalchemy/functions`

```python
class from_iso8601_timestamp(expression.FunctionElement):
    name = "from_iso8601_timestamp"
    inherit_cache = True

@compiles(from_iso8601_timestamp, "trino")
def compile_from_iso8601_timestamp(element, compiler, **kw):
    return f"from_iso8601_timestamp({compiler.process(element.clauses, **kw)})"
```

Then, the functions can be used like below

```python
query = (
    select(Table)
    .where(Table.created_at >= from_iso8601_timestamp(time))
)
```

If there is another way to archive this other than defining the custom functions by user side, please correct me. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by hashhar** [comment]
SqlAlchemy already seems to provide `func` generator.
Can you check if works for your case?

See https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#using-postgresql-full-text-functions-and-operators-directly for examples with PostgreSQL.

None of the SQLAlchemy dialects register remote functions by themselves, the user either defines them like you did using `FunctionElement` or using `func` or using `GenericFunction` (see https://docs.sqlalchemy.org/en/20/core/functions.html).

As such we don't expect to add functions for all functions which exist in Trino to the dialect itself.
