### ISSUE TITLE
ORM support for engine without catalog 

### ISSUE THREAD

**Issue by olp966220** [trinodb/trino-python-client#427]
### Describe the feature

I use url : trino://<username>:<password>@<host>:<port> to create engine and execute sql like 'SELECT * FROM catalog.shema.table', and it worked.

But when I try to use this url to do ORM operation, it can't get metadata or tables, for example:

1. get metadata:
> metadata = Metadata(schema='catalog.schema')
> metadata.reflect(bind=engine)
> metadata.tables
`FacadeDict({}) # Shows it get none metadata by schema='catalog.schema'`
2. get table:
> metadata = Metadata(schema='catalog.schema')
> table = Table('table', metadata, autoload=True, autoload_with=engine)
`sqlalchemy.exc.NoSuchTableError: schema=catalog.schema, table=table`
------
I tried sql on 2 catalog and it worked: 
> SELECT * FROM catalog1.shema.table UNION ALL SELECT * FROM catalog2.shema.table 

But I also want to operate different ORM from different catalogs but use same engine, so I can operate like this:
> session.query(ORM1, ORM2)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hovaesco** [comment]
- Get Metadata, you need to connect to specific catalog in order to get all tables from, because it executes https://github.com/trinodb/trino-python-client/blob/master/trino/sqlalchemy/dialect.py#L228-L235 so it's not supported at the moment.
- Get Table, you can use `trino_catalog` like:
```py
table_with_catalog = Table(
    'nation',
    metadata,
    Column('nationkey', Integer),
    schema='tiny',
    trino_catalog='tpch',
)
