### ISSUE TITLE
Cannot connect to Trino via OAUTH2 with SSO credentials

### ISSUE THREAD

**Issue by matialm** [trinodb/trino-python-client#444]
### Discussed in https://github.com/trinodb/trino-python-client/discussions/437

<div type='discussions-op-text'>

<sup>Originally posted by **lejanco** January 18, 2024</sup>
I am trying to connect to trino via oauth2 using the externalauthentication instructions in the README(e.g. keyring). I have tried (what seems like) everything. You can see the commented out efforts here as well.  I have done the pip install 'trino[<keyring>]'

` trino_connection = trino.dbapi.connect(host=host,
                                               port=port,
                                               user=username,
                                               catalog=catalog,
                                               schema=schema,
                                               auth=trino.auth.OAuth2Authentication(
                                                   # redirect_auth_url_handler=redirect_auth_url_handler
                                               ),
                                               http_scheme=http_scheme,
                                               # verify=False,
                                               # extra_credential=[('user', username),
                                               #                   ('password', password),
                                               #                   ("SSL", "true"),
                                               #                   ("SSLVerification", "NONE"),
                                               #                   ("externalAuthentication", "true")
                                               #                   ]
                                               )`

The debug suggests the token is being retrieved but not being authenticated. Help is greatly appreciated, but please limit suggestions that require admin rights to trino as I do not have that authorization. Thanks:

DEBUG:
</div>

**Comment by matialm** [comment]
PR created
https://github.com/trinodb/trino-python-client/pull/445

**Comment by hashhar** [comment]
Useful discussion about what the root cause was can be found at https://github.com/trinodb/trino-python-client/pull/445#issuecomment-1982806130
