### ISSUE TITLE
Client send empty session when user do not set session

### ISSUE THREAD

**Issue by starry225** [trinodb/trino-python-client#465]
### Expected behavior

client only send session when session is set by users

### Actual behavior

client send empty session if no session is set by users
![image](https://github.com/trinodb/trino-python-client/assets/14932809/c2f18f2b-c3f9-4e30-8162-31782fb2974a)

in client, it doesn't check if session exists

+ if self._client_session.properties:
            headers[constants.HEADER_SESSION] = ",".join(
                # ``name`` must not contain ``=``
                "{}={}".format(name, urllib.parse.quote(str(value)))
                for name, value in self._client_session.properties.items()
            )

### Steps To Reproduce

can be reproduced by init a connection and send a request.
or add a unit test in test_client

```
def test_request_session_properties_headers(mock_get_and_post):
    get, post = mock_get_and_post

    req = TrinoRequest(
        host="coordinator",
        port=8080,
        client_session=ClientSession(
            user="test_user",
        )
    )

    def assert_headers(headers):
        assert constants.HEADER_SESSION not in headers
```

### Operating System

amazon linux 2

### Trino Python client version

0.328.0

### Trino Server version

449

### Python version

3.7.16

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by hashhar** [comment]
Why is this a problem?

Feel free to send a PR to omit the header altogether if you want.

**Comment by hashhar** [comment]
Closing since this is not considered an issue.
