### ISSUE TITLE
Add support for asyncio

### ISSUE THREAD

**Issue by ggreg** [trinodb/trino-python-client#5]

**Comment by phanikumv** [comment]
Since we use Trino Python client for Airflow, and plan to build an asyncio compatible operator, it would benefit the Airflow user community if there is support for asyncio

**Comment by hashhar** [comment]
There are no plans to add asyncio compatible client for now. Closing for now. We can revisit this in future.

For now there is an `aiotrino` client available outside of the main project for people who want to try out asyncio.
