### ISSUE TITLE
Document how to use self-signed certificates with trino-python-client

### ISSUE THREAD

**Issue by fanglu-wish** [trinodb/trino-python-client#52]
Followed the instructions [LDAP Authentication](https://prestosql.io/docs/current/security/ldap.html) to deploy a LDAP presto cluster 

Installed presto-python-client 0.301.0

```

> conn = presto.dbapi.connect(
    host='<presto-ldap host name>',
    port=8443,
    user='<username>',
    catalog='hive',
    schema='default',
    http_scheme='https',
    auth=presto.auth.BasicAuthentication("<username>", "<password>"),
)

> cur = conn.cursor()

> cur.execute('show schemas')

```
But Got the following exception
`SSLError: HTTPSConnectionPool(host='presto-ldap.service.us-west-2b.consul', port=8443): Max retries exceeded with url: /v1/statement (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))`

According to the doc [LDAP Authentication](https://prestosql.io/docs/current/security/ldap.html), need to create a jks file and set up the two configurations 
```
http-server.https.keystore.path=/etc/presto_keystore.jks
http-server.https.keystore.key=keystore_password
```
So in presto-python-client, how to pass the jks file and password while connecting the LDAP presto cluster?

**Comment by findepi** [comment]
Can you please see https://github.com/prestosql/presto-python-client/pull/31 (https://github.com/prestosql/presto-python-client/issues/29)?

**Comment by hashhar** [comment]
LDAP works and is documented now at https://github.com/trinodb/trino-python-client#basic-authentication.

But we are still missing docs for how to use with clusters that use self-signed certs so renamed the issue.
