### ISSUE TITLE
Support Python 2 unicode type for query parameters

### ISSUE THREAD

**Issue by findepi** [trinodb/trino-python-client#53]

**Comment by findepi** [comment]
See prior discussion here: https://github.com/prestosql/presto-python-client/pull/51/files#r506159658

**Comment by moar55** [comment]
Can I take this?

**Comment by findepi** [comment]
This requires https://github.com/prestosql/presto-python-client/pull/51 first.

**Comment by findepi** [comment]
Dropped in favor of https://github.com/trinodb/trino-python-client/issues/4
