### ISSUE TITLE
Infinity and nan functions return strings instead of floats

### ISSUE THREAD

**Issue by rushton** [trinodb/trino-python-client#54]
## Problem

the values returned from infinity and nan functions in presto get cast to strings in python. 

## Reproduction

```
cursor.execute("SELECT infinity(), nan()")
rows = cursor.fetchall()

type(rows[0][0]) # => str
type(rows[0][1]) # => str
```

these should return the python `float("inf")` and `float("nan")` respectively.

**Comment by findepi** [comment]
@rushton are you planning to continue work on your PR (https://github.com/trinodb/trino-python-client/pull/55)?

**Comment by rushton** [comment]
@findepi will close my MR for now, didn't have the time to dig into a better solution.
