### ISSUE TITLE
Python client does not support SET ROLE

### ISSUE THREAD

**Issue by sbakiu** [trinodb/trino-python-client#7]
While using python client, it is not possible to enable `admin` role by executing:
`SET ROLE admin`

However, everything works fine while using `presto-cli`.

I am using Presto 329 and python-client 0.7.0.

**Comment by esemeniuc** [comment]
Same issue on latest trino library!

**Comment by esemeniuc** [comment]
Quick demo to connect to Trino using mutual auth with a custom role
```
import trino

conn = trino.dbapi.connect(
    host='localhost',
    port=8080,
    user='testuser',
    catalog='hive',
    http_scheme='https',
    verify='/home/user/Downloads/cacerts.pem',
    http_headers={'X-Trino-Role': 'hive=ROLE{admin}'} #you can also do `hive=ALL` or hive=`NONE`, see https://github.com/trinodb/trino/blob/fe608f2723842037ff620d612a706900e79c52c8/core/trino-main/src/test/java/io/trino/server/TestHttpRequestSessionContext.java#L63-L65
)

conn._http_session.cert = ('client.pem', 'client-key.pem') #for mutual auth

cur = conn.cursor()
cur.execute('SHOW schemas')
print("all schemas:", cur.fetchall())
```

**Comment by hashhar** [comment]
@esemeniuc Thanks for providing a workaround that's useful in some cases.

Can you also share what the error looks like in case of trying to execute a `SET ROLE` query?

**Comment by esemeniuc** [comment]
Running `SET ROLE admin` had no effect. I checked using the `JSON` tab in the web ui, and the navigated to `session.roles.CATALOG`, which was empty

**Comment by hashhar** [comment]
This requires the code in `client.py` to respect the `X-Trino-Set-Role` response header as documented at https://trino.io/docs/current/develop/client-protocol.html?highlight=role.

The value from the response header should be sent in all subsequent requests as the `X-Trino-Role` header.
It shouldn't be very difficult to implement - do you want to take an attempt @esemeniuc since nobody else isn't working on this yet?

**Comment by esemeniuc** [comment]
I won't be able to work on it for the foreseeable future, but thank you for the opportunity. I just wanted to help others who need a workaround

**Comment by ulisesojeda** [comment]
Hi @hashhar. I can work on it if it's not implemented yet

**Comment by Btwitzke** [comment]
Is there any documentation now on how to properly set the role in the connection now? I previously used the work-around above using the http_header but that is not allowed now on this most recent version as it is a 'reserved' header. If I call 'set role ROLE' as a query it does not persist through into my queries and permission is denied.

**Comment by aksakalli** [comment]
> Is there any documentation now on how to properly set the role in the connection now? I previously used the work-around above using the http_header but that is not allowed now on this most recent version as it is a 'reserved' header. If I call 'set role ROLE' as a query it does not persist through into my queries and permission is denied.

I agree. I created an issue for it. https://github.com/trinodb/trino-python-client/issues/230
