### ISSUE TITLE
Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5acbe9e20>: Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by PlutarcoII** [trinodb/trino-python-client#75]
Hi,

I'm experiencing an Issue when I'm trying to connect Trino:

TRINO_VERSION = 351

RUNNING ON DOCKER:
```
FROM openjdk:11.0-jre

# Trino version will be passed in at build time
ARG TRINO_VERSION

# Set the URL to download
ARG TRINO_BIN=https://repo1.maven.org/maven2/io/trino/trino-server/${TRINO_VERSION}/trino-server-${TRINO_VERSION}.tar.gz

# Update the base image OS and install wget and python
RUN apt-get update
RUN apt-get install -y wget python less

# Download Trino and unpack it to /opt/trino
RUN wget ${TRINO_BIN}
RUN mkdir -p /opt
RUN tar -xf trino-server-${TRINO_VERSION}.tar.gz -C /opt
RUN rm trino-server-${TRINO_VERSION}.tar.gz
RUN ln -s /opt/trino-server-${TRINO_VERSION} /opt/trino

# Copy configuration files on the host into the image
COPY etc /opt/trino/etc

# Download the Trino CLI and put it in the image
RUN wget https://repo1.maven.org/maven2/io/trino/trino-cli/${TRINO_VERSION}/trino-cli-${TRINO_VERSION}-executable.jar
RUN mv trino-cli-${TRINO_VERSION}-executable.jar /usr/local/bin/trino
RUN chmod +x /usr/local/bin/trino

# Specify the entrypoint to start
EXPOSE 8080
ENTRYPOINT /opt/trino/bin/launcher run
```

ATTACH DOCKER:
`docker exec -it trino_trino_1 trino`

RUN QUERY:
`trino> select clave, nombre from mysql.database.table;`

**works fine!**

**Trino Overview works great:**
http://0.0.0.0:8080/ui/

PYTHON FASTAPI CLIENT:

```
import logging
import trino

import pandas as pd
import numpy as np
import unidecode
import re
import json
import os
import io

import time
from time import sleep
from datetime import datetime
from dateutil.parser import parse

from fastapi import FastAPI, Request, Response
from fastapi.responses import FileResponse
from fastapi.responses import HTMLResponse
from fastapi.responses import StreamingResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

trino.client.logger.setLevel(logging.DEBUG)

app = FastAPI()

@app.get("/test")
async def root():

    conn = trino.dbapi.connect(
        host='0.0.0.0',
        port=8080
    )
    cur = conn.cursor()
    cur.execute('select clave, nombre from mysql.database.table;')
    rows = cur.fetchall()
    print(rows)
    jsonRes = { "status":"ok"}
    return jsonRes

```

Traceback (most recent call last):
replicator_1  | INFO:     172.20.0.1:34920 - "GET /test HTTP/1.1" 500 Internal Server Error
replicator_1  | ERROR:    Exception in ASGI application
replicator_1  | Traceback (most recent call last):
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
replicator_1  |     result = await app(self.scope, self.receive, self.send)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
replicator_1  |     return await self.app(scope, receive, send)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
replicator_1  |     await super().__call__(scope, receive, send)  # pragma: no cover
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/starlette/applications.py", line 111, in __call__
replicator_1  |     await self.middleware_stack(scope, receive, send)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
replicator_1  |     raise exc from None
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
replicator_1  |     await self.app(scope, receive, _send)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
replicator_1  |     raise exc from None
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
replicator_1  |     await self.app(scope, receive, sender)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/starlette/routing.py", line 566, in __call__
replicator_1  |     await route.handle(scope, receive, send)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
replicator_1  |     await self.app(scope, receive, send)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
replicator_1  |     response = await func(request)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/fastapi/routing.py", line 202, in app
replicator_1  |     dependant=dependant, values=values, is_coroutine=is_coroutine
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
replicator_1  |     return await dependant.call(**values)
replicator_1  |   File "./main.py", line 38, in root
replicator_1  |     cur.execute('select clave, nombre from mysql.database.table;')
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/trino/dbapi.py", line 408, in execute
replicator_1  |     result = self._query.execute()
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/trino/client.py", line 517, in execute
replicator_1  |     response = self._request.post(self._sql, additional_http_headers)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/trino/client.py", line 345, in post
replicator_1  |     proxies=PROXIES,
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/trino/exceptions.py", line 131, in decorated
replicator_1  |     raise error
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/trino/exceptions.py", line 118, in decorated
replicator_1  |     result = func(*args, **kwargs)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
replicator_1  |     return self.request('POST', url, data=data, json=json, **kwargs)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
replicator_1  |     resp = self.send(prep, **send_kwargs)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
replicator_1  |     r = adapter.send(request, **kwargs)
replicator_1  |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
replicator_1  |     raise ConnectionError(e, request=request)
replicator_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c8a3a6518>: Failed to establish a new connection: [Errno 111] Connection refused',))

I only requested it once.  Everything is working fine in Trino but python code is missing something.

**Comment by electrum** [comment]
You’re getting “Connection refused” which means the Python code can’t establish a TCP connection. I noticed `HTTPConnectionPool(host='localhost'` in the stack trace. Instead of `0.0.0.0` try using a real IP address.

**Comment by PlutarcoII** [comment]
> You’re getting “Connection refused” which means the Python code can’t establish a TCP connection. I noticed `HTTPConnectionPool(host='localhost'` in the stack trace. Instead of `0.0.0.0` try using a real IP address.

Thanks electrum...

Now is working as expected.
