### ISSUE TITLE
how to connect to two different catalogs using python client

### ISSUE THREAD

**Issue by sagar465** [trinodb/trino-python-client#78]
HI All,

Could someone help me if we can query two different catalogs using python clinet. I am able to do it using CLI, but not sure from python client. Thanks in advance. 

Regards,
Sagar Varma.

**Comment by findepi** [comment]
Absolutely! 

I will close this as answered.
We can continue conversation here, or on `#python-client` channel on [our slack](https://trino.io/slack.html).
See you there!
