### ISSUE TITLE
JWTAuthentication is missing on the last release

### ISSUE THREAD

**Issue by vitas** [trinodb/trino-python-client#99]
i have installed latest version via pip install and realised that JWTAuthentication class is missing.

**Comment by yuokada** [comment]
The last release was published about 8 months ago.
https://github.com/trinodb/trino-python-client/releases/tag/0.305.0

After JWTAuthentication class is created, we might not publish a new package.
https://github.com/trinodb/trino-python-client/commit/f638b935fb2ae805a18739e3d0378f4ab1ae26c0

**Comment by vitas** [comment]
ok, could you publish it as new release?

**Comment by ebyhr** [comment]
Let me close this issue since it's not a bug. I would recommend joining the community Slack. There is a `#python-client` channel. https://trino.io/community.html
